#!/bin/bash -e

PROJECT=four
CLOJURE_VERSION=1.5.0-alpha3

rm -rf target
lein jar

cd target
zip -q $PROJECT.jar -d "META-INF/maven*" "META-INF/leiningen*" "*.class"
cd classes
zip -q ../$PROJECT.jar $PROJECT.class
cd ..
ls -la *.jar
pack200  -G -Ustrip -r $PROJECT.jar
ls -la *.jar

java -cp ~/.m2/repository/org/clojure/clojure/$CLOJURE_VERSION/clojure-$CLOJURE_VERSION.jar:$PROJECT.jar $PROJECT
