#!/bin/bash -e

PROJECT=four
JAR=$PROJECT.jar
JAR_PG=$PROJECT-pg.jar
CLOJURE_VERSION=1.5.0-alpha3
CLOJURE_JAR=~/.m2/repository/org/clojure/clojure/$CLOJURE_VERSION/clojure-$CLOJURE_VERSION.jar

rm -rf target
lein jar

cd target
rm -rf fullconf.pro
echo "-injars $JAR" >> fullconf.pro
echo "-libraryjars $CLOJURE_JAR" >>fullconf.pro
echo "-outjars $JAR_PG" >>fullconf.pro
cat ../conf.pro >>fullconf.pro
java -cp `lein classpath` proguard.ProGuard @fullconf.pro

mv $JAR $PROJECT-leiningen.jar
mv $JAR_PG $JAR

SIZE=`ls -l $JAR | awk '{print $5}'`
echo "$JAR $SIZE"

if [ $SIZE -gt 4096 ]; then
   echo "$JAR is too big"
   exit 1
fi

java -cp $CLOJURE_JAR:$JAR $PROJECT
