#!/bin/bash -e

PROJECT=four
JAR=$PROJECT.jar
JAR_OUT=$PROJECT-pg.jar
CLOJURE_VERSION=1.5.0-alpha3
CLOJURE_JAR=~/.m2/repository/org/clojure/clojure/$CLOJURE_VERSION/clojure-$CLOJURE_VERSION.jar

rm -rf target
lein jar

cd target
zip -q $JAR -d "META-INF/maven*" "META-INF/leiningen*" "*.class"
cd classes
zip -q ../$JAR $PROJECT.class
cd ..

rm -rf fullconf.pro
echo "-injars $JAR" >> fullconf.pro
echo "-libraryjars $CLOJURE_JAR" >>fullconf.pro
echo "-outjars $JAR_OUT" >>fullconf.pro
cat ../conf.pro >>fullconf.pro
java -cp `lein classpath` proguard.ProGuard @fullconf.pro

SIZE=`ls -l $JAR_OUT | awk '{print $5}'`
echo "$JAR_OUT $SIZE"

if [ $SIZE -gt 4096 ]; then
   echo "$JAR_OUT is too big"
   exit 1
fi

java -cp $CLOJURE_JAR:$JAR_OUT $PROJECT
